import React from 'react';

const Fees: React.FC = () => {
  return (
    <section id="fees" className="py-16 sm:py-20 bg-gray-50">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="rounded-3xl border border-gray-200 bg-white p-8 sm:p-12">
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
            <div className="lg:col-span-2">
              <h2 className="text-3xl sm:text-4xl font-extrabold text-gray-900">Fees & transparency</h2>
              <p className="mt-4 text-lg text-gray-700">
                We only take a small share of performance: <span className="font-semibold text-gray-900">1% of profit</span> generated by shop sales.
              </p>
              <ul className="mt-6 space-y-3 text-gray-700">
                <li className="flex items-start"><span className="mt-1 mr-3 h-2.5 w-2.5 rounded-full bg-primary-500" />No management fees. No hidden fees.</li>
                <li className="flex items-start"><span className="mt-1 mr-3 h-2.5 w-2.5 rounded-full bg-primary-500" />Withdraw anytime. No lock-in periods.</li>
                <li className="flex items-start"><span className="mt-1 mr-3 h-2.5 w-2.5 rounded-full bg-primary-500" />Real-time balance updates from actual shop performance.</li>
              </ul>
            </div>
            <div className="lg:col-span-1">
              <div className="rounded-2xl border border-primary-200 bg-primary-50 p-6">
                <h3 className="text-xl font-semibold text-gray-900">Example</h3>
                <p className="mt-2 text-gray-700">If a shop makes $100 profit in a day:</p>
                <ul className="mt-4 space-y-2 text-gray-700">
                  <li>• Investors share: <span className="font-semibold">$99</span></li>
                  <li>• NhavaGX (1% of profit): <span className="font-semibold">$1</span></li>
                </ul>
                <p className="mt-4 text-sm text-gray-600">Returns vary by shop performance; no fixed or guaranteed rates.</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default Fees;


